### ISSUE TITLE
After copying folder to plugins directory, it is not loading

### ISSUE THREAD

**Issue by kgolding** [creecros/Group_assign#27]

**Comment by kgolding** [comment]
I downloaded the plugin as a zip, unzipped it, then transferred the "Group_assign-master" folder to the plugins directory the plugin wasn't loading.
Renaming the directory to "Group_assign" got it working.

**Comment by creecros** [comment]
Yes, it must be named Group_assign. In all practicality, you should not master repos as the install, you should use the release:
https://github.com/creecros/Group_assign/releases

and if you use the supplied release file, i.e.: https://github.com/creecros/Group_assign/releases/download/1.6.1/Group_assign-1.6.1.zip

the folder is named appropriately.

**Comment by kgolding** [comment]
Agreed! Might be worth adding a install section to the Readme?
