### ISSUE TITLE
Undefined index in Model/NewUserNotificationFilterModel.php

### ISSUE THREAD

**Issue by grayed** [creecros/Group_assign#28]
Just found the following in Kanboard CLI worker logs, repeated many times:

PHP Notice:  Undefined index: owner_ms in /var/www/kanboard-1.2.8/plugins/Group_assign/Model/NewUserNotificationFilterModel.php on line 192
PHP Notice:  Undefined index: owner_gp in /var/www/kanboard-1.2.8/plugins/Group_assign/Model/NewUserNotificationFilterModel.php on line 193

**Comment by creecros** [comment]
Do you have anyothe plug-ins loaded that may be overriding the TaskFinderModel?

**Comment by creecros** [comment]
Or just list any other plug-ins you have loaded so I can look in to what's going on.

**Comment by grayed** [comment]
Here is full list of all installed plugins:

Calendar 1.1.0
CardPushDate 0.0.1
Gantt 1.0.4
Group_assign 1.6.1
OAuth2 1.0.1
Overwrite_translation 1.0.31.0
RabbitMQ 1.0.0
Subtaskdate 1.0.1
Telegram 1.3.0

**Comment by grayed** [comment]
I've also did a quick grep for TaskFinderModel in all plugins installed, and it was only found in Group_assign one.

**Comment by creecros** [comment]
Roger. I'll take a look into it next chance I get.

Last question, though, mysql, sqlite, or postgres? Or just copy paste system configuration.

**Comment by grayed** [comment]
SQLite. The full config.php contents as follows:
```
define('DATA_DIR', __DIR__.DIRECTORY_SEPARATOR.'data');
define('DEBUG', false);
define('LOG_DRIVER', 'file');
define('LOG_FILE', DATA_DIR.DIRECTORY_SEPARATOR.'debug.log');
define('PLUGINS_DIR', __DIR__.DIRECTORY_SEPARATOR.'plugins');
define('PLUGIN_API_URL', 'https://kanboard.org/plugins.json');
define('PLUGIN_INSTALLER', true);
define('CACHE_DRIVER', 'memory');
define('CACHE_DIR', DATA_DIR.DIRECTORY_SEPARATOR.'cache');
define('FILES_DIR', DATA_DIR.DIRECTORY_SEPARATOR.'files');
define('MAIL_CONFIGURATION', false);
define('MAIL_FROM', '%HIDDEN%');
define('MAIL_TRANSPORT', 'smtp');
define('MAIL_SMTP_HOSTNAME', 'localhost');
define('MAIL_SMTP_PORT', 25);
define('MAIL_SMTP_USERNAME', '');
define('MAIL_SMTP_PASSWORD', '');
define('MAIL_SMTP_ENCRYPTION', null); // Valid values are "null", "ssl" or "tls"
define('MAIL_SENDMAIL_COMMAND', '%HIDDEN%');
define('DB_RUN_MIGRATIONS', false);
define('DB_DRIVER', 'sqlite');
define('DB_USERNAME', 'root');
define('DB_PASSWORD', '');
define('DB_HOSTNAME', 'localhost');
define('DB_NAME', 'kanboard');
define('DB_PORT', null);
define('DB_SSL_KEY', null);
define('DB_SSL_CERT', null);
define('DB_SSL_CA', null);
define('DB_VERIFY_SERVER_CERT', null);
define('DB_TIMEOUT', null);
define('LDAP_AUTH', false);
define('LDAP_SERVER', '');
define('LDAP_PORT', 389);
define('LDAP_SSL_VERIFY', true);
define('LDAP_START_TLS', false);
define('LDAP_USERNAME_CASE_SENSITIVE', false);                                                                                                                             
define('LDAP_BIND_TYPE', 'anonymous');                                                                                                                                     
define('LDAP_USERNAME', null);
define('LDAP_PASSWORD', null);
define('LDAP_USER_BASE_DN', '');
define('LDAP_USER_FILTER', '');
define('LDAP_USER_ATTRIBUTE_USERNAME', 'uid');
define('LDAP_USER_ATTRIBUTE_FULLNAME', 'cn');
define('LDAP_USER_ATTRIBUTE_EMAIL', 'mail');
define('LDAP_USER_ATTRIBUTE_GROUPS', 'memberof');
define('LDAP_USER_ATTRIBUTE_PHOTO', '');
define('LDAP_USER_ATTRIBUTE_LANGUAGE', '');
define('LDAP_USER_CREATION', true);
define('LDAP_GROUP_ADMIN_DN', '');
define('LDAP_GROUP_MANAGER_DN', '');
define('LDAP_GROUP_PROVIDER', false);
define('LDAP_GROUP_BASE_DN', '');
define('LDAP_GROUP_FILTER', '');
define('LDAP_GROUP_USER_FILTER', '');
define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');
define('REVERSE_PROXY_AUTH', false);
define('REVERSE_PROXY_USER_HEADER', 'REMOTE_USER');
define('REVERSE_PROXY_DEFAULT_ADMIN', '');
define('REVERSE_PROXY_DEFAULT_DOMAIN', '');
define('REMEMBER_ME_AUTH', true);
define('ENABLE_HSTS', true);
define('ENABLE_XFRAME', false); // tweaked to allow Owncloud authorization
define('MARKDOWN_ESCAPE_HTML', true);
define('API_AUTHENTICATION_HEADER', '');
define('ENABLE_URL_REWRITE', true);
define('HIDE_LOGIN_FORM', false);
define('DISABLE_LOGOUT', false);
define('BRUTEFORCE_CAPTCHA', 3);
define('BRUTEFORCE_LOCKDOWN', 6);
define('BRUTEFORCE_LOCKDOWN_DURATION', 15);
define('SESSION_DURATION', 0);
define('HTTP_PROXY_HOSTNAME', '');
define('HTTP_PROXY_PORT', '3128');
define('HTTP_PROXY_USERNAME', '');
define('HTTP_PROXY_PASSWORD', '');
define('HTTP_VERIFY_SSL_CERTIFICATE', true);
define('TOTP_ISSUER', 'Kanboard');
define('EXTERNAL_AUTH_EXCLUDE_FIELDS', 'username');
```

**Comment by creecros** [comment]
@grayed 

What I meant by system config:
```
Configuration
Application version: 1.2.8
PHP version: 7.2.14
PHP SAPI: fpm-fcgi
OS version: Linux 4.9.45-rancher
Database driver: sqlite
Database version: 3.26.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
```

I have been completely unsuccessful at duplicating your error, could you give me any more info, like, when it does it?

**Comment by creecros** [comment]
My suspicion is, it has something to do with running background workers. I don't run background workers, and am pretty clueless in regards to that, and I also run kanboard in docker on a rancher server, so I'm not even sure I can setup a test environment to do that.

I'll leave the issue open, in hopes that someone else can figure out what the issue is.

**Comment by grayed** [comment]
Ah, sorry, here is system info:
```
Application version: 1.2.8
PHP version: 7.2.13
PHP SAPI: fpm-fcgi
OS version: OpenBSD 6.4
Database driver: sqlite
Database version: 3.24.0
Browser: Mozilla/5.0 (X11; OpenBSD amd64; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
```
Yes, I use background workers. And I don't see those messages anymore as well. I suspect the issued was related to PHP version I was using before (it was 7.0.smth.)... I'll update this issue if I'll ever find anything more.

Thank you for your time and patience.

**Comment by creecros** [comment]
PHP version has been tested down to version 5.6.3, definately not that.

Have you ever used any previous versions of this plugin, or 1.6.1 only?

**Comment by grayed** [comment]
Well, I don't say PHP was the cause, but it could be a trigger...

No, I've started using it immediately with 1.6.1. But other plugins as well as Kanboard itself were being updated from time to time, the Group_assign is the newest one here.

**Comment by creecros** [comment]
Who knows, at this point, if you encounter it again and can make a correlation, just update here with some info.

Just looking at the error, it is clear to me that the $event_data that was sent to the NewUserNotificationFilterModel.php, did not contain owner_ms or owner_gp. I can't think of how that would even be possible, unless it was happening and the schema hadn't updated, or perhaps the background worker is going through a different route, but you say it's not doing it anymore...so now it is? Just doesn't make any sense to me. I think it was a fluke. ;) Nothing to see here.

**Comment by creecros** [comment]
https://kanboard.discourse.group/t/cron-job-error-messages/381/7

**Comment by creecros** [comment]
https://github.com/creecros/Group_assign/releases/tag/1.7.1
 prevents the warnings, but I wouldn't expect it to actually solve whatever the issue truly is.
