### ISSUE TITLE
Group list not showing when create a new task

### ISSUE THREAD

**Issue by btd1337** [creecros/Group_assign#29]
When trying to create a new task, only the 'Unassigned' option is loaded in the dropdown list.

![Captura de tela de 2019-04-05 02-49-44](https://user-images.githubusercontent.com/11943860/55606008-84958300-574d-11e9-8079-243d4ce6e769.png)

Obs: Groups are OK

![Captura de tela de 2019-04-05 02-51-19](https://user-images.githubusercontent.com/11943860/55606051-ba3a6c00-574d-11e9-80da-993acf8c0d9c.png)

**Comment by creecros** [comment]
Probably because you made some groups, but never actually gave them permissions for the project you are trying to assign them too.

Just a guess...

**Comment by btd1337** [comment]
That's this! 

Please, it would be interesting to add this information to the README.

...And congratulations on this great work!

**Comment by creecros** [comment]
It's in the README.
"Can only assign groups or other assigness to a task that have permissions in the Project."

This plugin does nothing in regards to the process of assigning permissions:
https://docs.kanboard.org/en/latest/user_guide/projects.html#project-permissions
