### ISSUE TITLE
Kanboard turn down after upgrade

### ISSUE THREAD

**Issue by btd1337** [creecros/Group_assign#32]
After upgrade plugin to version 1.6.2, the Kanboard return ERROR 500.

Deleting a Plugin Folder, Kanboard normally opens.

**Comment by creecros** [comment]
Any more info? Whats the log say?

Works fine for me:
https://projects.nachostudio.ml

admin
admin

**Comment by creecros** [comment]
oh, i lied, I found it. I'll re-release first chance i get

**Comment by creecros** [comment]
all set.
