### ISSUE TITLE
duplicate projects and tasks

### ISSUE THREAD

**Issue by vmalaga** [creecros/Group_assign#36]
Hi.

I have a new installed kanboard, and after install the **Group_assign** plugin, every action made on kanboard duplicates the action.

- New task on project creates 2 tasks with the same name
![Screenshot_20190527_100752](https://user-images.githubusercontent.com/500904/58405466-c369fa00-8067-11e9-844c-8bd0cf38750e.jpeg)
![Screenshot_20190527_100805](https://user-images.githubusercontent.com/500904/58405471-c6fd8100-8067-11e9-91d1-ceb4269992fb.jpeg)

- New project, created 2 projects with the same name
![Screenshot_20190527_101229](https://user-images.githubusercontent.com/500904/58405564-062bd200-8068-11e9-9338-4d7860a4802b.jpeg)
![Screenshot_20190527_101257](https://user-images.githubusercontent.com/500904/58405570-09bf5900-8068-11e9-8946-67eb8ead34c4.jpeg)

**Comment by vmalaga** [comment]
my Group_assign version is 1.7.1

**Comment by creecros** [comment]
Yes, I realized I made a mistake in version 1.7.0 and it continued in 1.7.1, I believe I fixed it with 1.7.2, upgrade and it should be fixed.

**Comment by vmalaga** [comment]
ok, upgraded to 1.7.2 and solved the problem.

thanks and great work
