### ISSUE TITLE
User filters not working

### ISSUE THREAD

**Issue by alvaradojao** [creecros/Group_assign#37]
Hello this is a great plugin, I see that once installed en Kanboard 1.5.9, the user filters does not working.

This is my project before user filter:

![image](https://user-images.githubusercontent.com/41443328/58560116-ab1dea80-81e1-11e9-8df6-607d7be16d85.png)
 and this after:

![image](https://user-images.githubusercontent.com/41443328/58560166-c7ba2280-81e1-11e9-870a-e4f58319b40b.png)

appreciate any help!

**Comment by creecros** [comment]
is that user in the assigned group?

**Comment by alvaradojao** [comment]
There is one project for some people, all them are part of the group, but when I filter by username, filter show the tasks assigned to him and other tasks assigned to other people of the group. 

The plugin in Kanboard 1.2.5 works pretty fine, this only happen in version 1.2.9.

**Comment by creecros** [comment]
is the person you are searching for, in the group?
![image](https://user-images.githubusercontent.com/26339368/58565683-20e37f80-81fd-11e9-8105-fe0e8652bde7.png)

if so, then the behavior is working as I intended it.

I could see how it could be undesired, so i'd have to think about how to remove that relationship without removing that feature.

**Comment by alvaradojao** [comment]
Yes he part of the group!  the filter is by username! I think when you filter by username is not useful see tasks assigned to another person.

**Comment by creecros** [comment]
> I think when you filter by username is not useful see tasks assigned to another person.

I can see it both ways. I'll have to think of a way to make everyone happy.

**Comment by alvaradojao** [comment]
Thanks!
