### ISSUE TITLE
Hot keys don't work after install this plugin

### ISSUE THREAD

**Issue by GusevVictor** [creecros/Group_assign#38]
I think this is very best plugin, but after I have install it the following hot keys don't work.

**The keys are:** 

- Ctrl+Enter to send task
- E - for edit a task
- S - for create a subtask
May be other hot keys

I have tested it when I deinstall this plugin. After deinstall the plugin hot keys work again. After install plugin again - no.

**Craig Crosby** 1.7.3
**Application version:** 1.2.9
**PHP version:** 7.2.17-0ubuntu0.18.04.1
**PHP SAPI:** apache2handler
**OS version:** Linux 4.15.0-50-generic
**Database driver:** postgres
**Database version:** 10.8 (Ubuntu 10.8-0ubuntu0.18.04.1)
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

Thank a lot for this plugin

Best regards,
Viktor.

**Comment by creecros** [comment]
I never would have thought to test that, I've never used a hot key...

I have my suspicions as to what may be causing it. I'll see what I can do when I get a moment.

Stay tuned.

**Comment by GusevVictor** [comment]
I'll wait for your answer to me. Hot keys is very very good if use kanboard from day to day basis.

THANK you!

**Comment by creecros** [comment]
https://github.com/creecros/Group_assign/releases/tag/1.7.4

double test if for me, and let me know
