### ISSUE TITLE
Wishlist: compact mode / customizability of the appearance of "Other Assignees" in board view cards

### ISSUE THREAD

**Issue by nekohayo** [creecros/Group_assign#39]
This is the spiritual successor to https://github.com/creecros/Customizer/issues/89, where it was made possible to set the size of the avatar of the main assignee in the board view.

One could think we could do similar functionality for the "Other Assignees", allow setting their avatar sizes and call it a day. But I think we can do better/smarter, for those looking for a minimalistic and space-efficient visual representation.

If we were to just jack up the size of the avatars, and still keep them on a row below the main avatar and besides the "**Other Assignees:**" label, then we would hit space constraints pretty fast, and it would look a bit chaotic too.

My proposal is therefore, either as a "compact mode" setting or, maybe as the default behavior (i.e. a bold design decision, which would also reduce the code paths), to hide both the "Other Assignees" label and main assignee name label, instead offering to show all the avatars as one big line (primary assignee, then the secondary assignees) in a bigger configurable size, like what you see on various other apps out there. If you want to differentiate between the primary and secondary assignees (besides the primary always being the first on the line), you could do so in a subtle way, for example with a 1px border around it or by making the secondary ones partially transparent (maybe 80-90% opaque?) or grayscale/desaturated (if CSS has a property for that).

As an example, this is what Trello (arguably the most popular kanban-like app in the mass market) looks like, notice the quarter-rounded (not fully rounded) avatars stacked next to each other inside the card view:

![trello-tour-board_fr cropped](https://user-images.githubusercontent.com/479401/59546636-465fd100-8eff-11e9-89e9-45784bd39ed4.jpg)

It looks damned clean/zen, and it lets the cards remain vertically compact.

**Comment by creecros** [comment]
I'll see what I can do here, but will say, CSS/HTML is not my forte, kenlog did most of that in Customizer. Changing size, easy for me, arrangement, I'm really not the guy.

**Comment by BlueTeck** [comment]
With PR #41 it is possible to hide the labels on the card via CSS (which makes the card layout more campact)

**Comment by creecros** [comment]
https://github.com/BlueTeck/kanboard_plugin_boardcustomizer

.boom{!}

**Comment by Jieiku** [comment]
I have done some more work in this regard: https://github.com/Jieiku/Group_assign/releases/tag/1.8.0
