### ISSUE TITLE
Can't unassign Other Assignees?

### ISSUE THREAD

**Issue by nekohayo** [creecros/Group_assign#40]
I have a task set up with Assignee, Assigned Group, and Other Assignees (all at once, for testing!). It roughly looks like this when editing it:

![Screenshot from 2019-06-27 14-47-48](https://user-images.githubusercontent.com/479401/60292365-eac41900-98ea-11e9-97f5-a55d3ad71aac.png)

While I can unassign the group, there is a bug where I cannot unassign the "Other Assignees". If I try to unassign the two "Other Assignees" at once, it does nothing.

**Comment by creecros** [comment]
I think that got it. I've always been a bad tester, so let me know if it does anything else buggy.
