### ISSUE TITLE
Shared tasks doesn't show for other assignees

### ISSUE THREAD

**Issue by rnorden** [creecros/Group_assign#42]
Kanboard: 1.2.6
Plugin: 1.7.4

Given
a task for User A,

When
adding User B to 'Other Assignees'

Then
the card should show up for User A & User B.

However the card doesn't show up on User B's board filtered by "assignee:me".

**Comment by creecros** [comment]
You are probably correct, assignee: me feature would have been moved to allasignee:me, after 1.7.3.

https://github.com/creecros/Group_assign/releases/tag/1.7.3

I can look into adding only that back, but allasignee:me would be the same, so might just change that in the readme.

**Comment by creecros** [comment]
I also advise updating to 1.7.5, 1.7.4 had an issue with removing assignees from the pillbox.
