### ISSUE TITLE
Filter assignee:GroupName doesn't work

### ISSUE THREAD

**Issue by BlueTeck** [creecros/Group_assign#43]
Hi @creecros,
the readme says that assignee:GroupName should work.
Unfortunately it doesn't:

![image](https://user-images.githubusercontent.com/1961634/62054424-d9d43380-b219-11e9-8e95-776d131e91e6.png)

Filter assignee:"XFT_Berater" or assignee:XFT_Berater doesn't return any result :/

Could you please check, maybe I made a mistake?

**Comment by creecros** [comment]
It might have also moved when I separated the filters, try `allassignees:groupname`

If that works, I'll update the readme, if not, I'll take a look.

**Comment by BlueTeck** [comment]
allassignees:groupname seems to be working
