### ISSUE TITLE
enhance filterbar by groups

### ISSUE THREAD

**Issue by BlueTeck** [creecros/Group_assign#45]
Hi @creecros,

what do you think about a new filter dropdown with all groups.

Might be possible with  template:project:header:after hook or a new hook is needed.

![image](https://user-images.githubusercontent.com/1961634/62058552-ed839800-b221-11e9-8e46-c3d11fbdf127.png)

Or enrich the user dropdown with groups?

Regards,
Timo

**Comment by creecros** [comment]
looks good to me. i would imagine the hook should work. i can take a look sometime soon.

**Comment by creecros** [comment]
Thanks for adding, by the way!
