### ISSUE TITLE
Error when filtering

### ISSUE THREAD

**Issue by Jandalf81** [creecros/Group_assign#48]
Hi there,

we are in the process of installing KanBoard. It works great so far, we just think we found a bug.

First, here's some information of our system:
* Version: 1.2.11
* PHP Version: 7.3.7
* PHP SAPI: cgi-fcgi
* HTTP-Client: cURL
* OS Version: Windows NT 10.0
* Datenbanktreiber: postgres
* Datenbank Version: 11.5
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
* MetaMagik 1.4.2
* Group_assign 1.7.8
* users per LDAP

Everything works, we can create new cards and assign more users and groups as designed. 
But then we get an error when we try to filter for the assigned group:
`Internal Error: SQL Error: SQLSTATE[22P02]: Invalid text representation: 7 FEHLER: ungültige Eingabesyntax für ganze Zahl: »« LINE 1: ...group_has_users WHERE group_has_users.user_id IN ('')) OR ta... ^`
See [errorlog.txt](https://github.com/creecros/Group_assign/files/3689815/errorlog.txt) for more details.

I _think_ the error is produced around line 102 in Filter/TaskAllAssigneeFilter.php. The variable _$useridstring_ seems to be empty which in turn invalidates the whole SQL statement. I don't know _why_, though.

Is there anything you need from us to find this bug?

**Comment by creecros** [comment]
Tell me exactly what you are putting in the search field.

**Comment by Jandalf81** [comment]
Thank you for taking the time to help me. Unfortunately, I will not be able top answer this question until monday. The Kanboard installation is at work and I can't reach it from home... ;-(

If I remember right, we did the following:
* created a new group called "Demonstration" directly in KanBoard
* added some LDAP users
* tried to filter via the new dropdown filter menu from the latest version => ERROR
* tried to filter via entering _allassignees:"Demonstration"_ into the filter box => ERROR

Something I forgot to mention is that we have another test installation which works as expected. The only errors (to my knowledge) are
* local users only (opposed to LDAP users)
* using SQLite (opposed to PostgreSQL)

Since we are talking about using KanBoard with a lot of existing users at work, we obviously want to use both LDAP and PostgreSQL...

**Comment by creecros** [comment]
I duplicated and will look into it:
`Internal Error: SQL Error: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type integer: "" LINE 1: ...group_has_users WHERE group_has_users.user_id IN ('')) OR ta... ^`

**Comment by creecros** [comment]
updating line 97 to: 
`$useridstring = intval(implode("','", $useridsarray));`

solves it, just want to run more tests and make sure it doesn't break anything on various setups.

**Comment by Jandalf81** [comment]
I can confirm that this fix at least doesn't break my SQLite installation. I have to wait for my admin to test the PostgreSQL installation, though...

**Comment by Jandalf81** [comment]
Today I can also confirm that this fixed the problem with our PostgreSQL installation. We haven't found new bugs but didn't test extensively, yet

**Comment by creecros** [comment]
Thanks for testing for me, I'll update the release next chance I get.

**Comment by Jandalf81** [comment]
I want to thank you for your fast help! I'll close this bug now as it seems to be resolved. We'll install the next "official" update as soon as it's ready.
