### ISSUE TITLE
Kanboard 1.12.2 new filter assignee:anybody doesn't works

### ISSUE THREAD

**Issue by Cyboulette** [creecros/Group_assign#49]
Hello,

The latest version of kanboard includes a new filter about assignee:anybody (see commits: https://github.com/kanboard/kanboard/commit/93dee80c04a4be2250680473313ec4bc7682ee55)

This filter seems to doesn't work with Group assign. Can you please check if it's only mine or if it's an issue?

Thanks :) !

**Comment by creecros** [comment]
If I can remember to turn my server back on before I leave for work, I will test.

**Comment by creecros** [comment]
works just fine:
https://projects.nachostudio.ml/
