### ISSUE TITLE
Assign to group in Recurrent task

### ISSUE THREAD

**Issue by mapeze** [creecros/Group_assign#5]
If there is a recurrence defined in a task assigned to a group, the new task created by the recurrence is not assigned to the group.

If the task with recurrence is assigned to a user, the new task created by the recurrence is assigned to that user. I expected the same behaviour when the task is assigned to a group.

**Comment by creecros** [comment]
will need a modified TaskDuplicationModel to do this.

**Comment by mapeze** [comment]
I realized after posting the issue.
We can close this.
I opened a feature request on Kanboard github https://github.com/kanboard/kanboard/issues/3937

**Comment by creecros** [comment]
It's a plug in feature, so it should be in the plugin

**Comment by creecros** [comment]
@mapeze 

just getting around to this, should be done soon. Just working out some minor details for moving and duplicating to other projects in regards to permissions.

**Comment by creecros** [comment]
That was actually a lot of work...

https://github.com/creecros/Group_assign/releases/tag/1.5.0
