### ISSUE TITLE
allassignees:nobody (campared to standard assignee:nobody)

### ISSUE THREAD

**Issue by BlueTeck** [creecros/Group_assign#52]
Hi @creecros,

There is a standard filter `assignee:nobody` which displays all task without assignee.

Maybe this would a nice addition for this plugin `allassignees:nobody` (no group or other asssignee).

Regards,
Timo

**Comment by creecros** [comment]
@BlueTeck 
should be easy enough:
https://github.com/creecros/Group_assign/blob/0ac70ea65b246b1663ee46d6743cc12484869cc4/Filter/TaskAllAssigneeFilter.php#L93

add the lines:
$this->query->eq(TaskModel::TABLE.'.owner_gp', 0);
$this->query->eq(TaskModel::TABLE.'.owner_ms', 0);

should do it? My server is offline so I can't test today.

**Comment by BlueTeck** [comment]
Changed and tested :)
