### ISSUE TITLE
New action: assign subtask assignee to task other assignees

### ISSUE THREAD

**Issue by BlueTeck** [creecros/Group_assign#53]
Hi @creecros,

what do you think about this action:

After a task or subtask is changed, assign all subtask assigness to task other assignees.

Regards,
Timo

**Comment by creecros** [comment]
Sounds good to me.

To make sure I understand:
- Task is updated/changed
- All subtask assignees are added to the "Other Assignees"
- What if they are removed from subtask assignee?

**Comment by BlueTeck** [comment]
> What if they are removed from subtask assignee?

I would suggest nothing will be removed automatically, or the action gets a parameter.

**Comment by creecros** [comment]
You adding? or you're asking me to look into it?

**Comment by BlueTeck** [comment]
I will do it, I just want your opinion, because it is your plugin 😉

**Comment by creecros** [comment]
Awesome!

I would also add a switch in the settings to turn it on, something like:
- [ ] Automaticly add subtask assignees to Other Assignees of the task

**Comment by creecros** [comment]
either add or don't.
