### ISSUE TITLE
SQL Injection ?

### ISSUE THREAD

**Issue by Cyboulette** [creecros/Group_assign#55]
Hello,

On the filter https://github.com/creecros/Group_assign/blob/master/Filter/TaskAllAssigneeFilter.php we can see that the plugin using the addCondition method from the ConditionBuilder of PicoDb.
In this method the plugin pass a custom SQL query with IN & SELECT, and try to find some usernames, names or ids corresponding to `$this->value` passed.

I have tested on my side, and if we are using the filter assignee:"Test'" a SQL error is displayed.

I think that this code need to prevent SQL injection. What do you think @creecros ?

Thanks!

**Comment by creecros** [comment]
I think that your comprehension is more than mine, I am truly not a coder, and I would welcome your contributions.

**Comment by cl0ne** [comment]
Shouldn't be there [in condition with subquery](https://github.com/elvanto/picodb#in-condition-with-subquery) used?

**Comment by creecros** [comment]
either make a pull request or don't.
