### ISSUE TITLE
Automatic actions didn't appear

### ISSUE THREAD

**Issue by Claytondiver** [creecros/Group_assign#6]
Hi @creecros , first of all, congratulations for creating this plugin, it´s indeed very useful.
I have a question: I don´t know why, but the 3 automatic actions didn't appear for me. I tried uninstall the plugin and reinstall it again, but they still not appearing... Any thoughts on that? My Kanboard version is 1.2.5.
Thanks in advance!

**Comment by Claytondiver** [comment]
BTW, I´ve also installed your SendEmailCreator plugin (version 0.0.2).

**Comment by creecros** [comment]
Just tested on 1.2.5, all 3 auto actions appear.
How are you installing?

**Comment by Claytondiver** [comment]
Thanks for your answer! 👍 

So, I asked our infrastructure guy how he did it and he told me that he used the command
_./cli plugin:install https://github.com/creecros/Group_assign/archive/0.0.1.zip_
After that, he just renamed the folder to "Group_assign"

He also told me to say to you that we are using a docker image and the plugins folder has the correct permissions...

See, I can assign a task to a group, this works fine. The only question is the automatic actions that didn´t appear in the combobox...

**Comment by Claytondiver** [comment]
Hi, after upgrading SendEmailCreator to version 0.0.4 the automatic actions appeared!
Thank you very much!

**Comment by creecros** [comment]
I also am using docker image. Tell your IT guy, not to install that way. The archive is not correct, and he needs to use the actual Release Zip, or simply install via Kanboard on the plugin page.

**Comment by creecros** [comment]
Send Email Creator and Group Assign are two different plugins and not even remotely linked, one issue will not solve the other.

The Actions you are looking for are:
![image](https://user-images.githubusercontent.com/26339368/43015363-90040316-8c1d-11e8-866b-38c6b18b6cd9.png)
![image](https://user-images.githubusercontent.com/26339368/43015373-9a7b0718-8c1d-11e8-9d4c-d213f9555a66.png)
![image](https://user-images.githubusercontent.com/26339368/43015384-a3b07f7a-8c1d-11e8-9a92-02a25194c7be.png)
