### ISSUE TITLE
Additional Automatic Action

### ISSUE THREAD

**Issue by Gatosan23** [creecros/Group_assign#66]
Hello,

I was wondering if it is possible to add an new Automatic Action, or expand on an existing one, which will send an E-Mail to a assigned group in a Task, when someone is changing something in that Task? For example when I attach a new document 
(PDF or a Picture) or change a category. It would be great if someone could help me with this. 

Many thanks in advance and best regards
Tom

**Comment by creecros** [comment]
I have no way to test it, and I'm going on memory.

I feel somewhat confident, if you just add the update event to the already existing EmailGroup action, it should achieve what you're asking.

`TaskModel::EVENT_UPDATE`

**Comment by Gatosan23** [comment]
Thank you so much for your help. As soon as I am able to try this, I will let you know how it works.

**Comment by creecros** [comment]
no problem
