### ISSUE TITLE
Broken (de_DE) Translation with installed Plugin

### ISSUE THREAD

**Issue by RainerBielefeld** [creecros/Group_assign#73]
I observed missing/wrong  Translation in "Overview" view with installed Plugin: 
`"The field "priority" have been updated"` 
instead of 
`Das Feld "priority" wurde verändert`
  
Root might be string "have been updated" instead of "has been updated"!

More details (screenshot, ..) see [here](https://tickets.kanban.bielefeldundbuss.de/?controller=TaskViewController&action=readonly&task_id=449&token=1fe7f29430a6532601dc9ef6ed0dfc4456c6bdebd5c40568d30aee9489ab)!

To be honest: I only collected some abnormalities, but still don't  understand ...

And something else I see, I can't tell whether related or not:
[German locale](https://github.com/creecros/Group_assign/blob/master/Locale/de_DE/translations.php) looks very incomplete compared to [pt_BR](https://github.com/creecros/Group_assign/blob/master/Locale/pt_BR/translations.php).

If you think we need a complete Translation.pho I can do the work, soon.

**Comment by creecros** [comment]
if you can fix it, great! I didn't add any translations, and dont speak german, so i wouldn't even know where to begin. I leave the translations to contributors who speak different languages.
