### ISSUE TITLE
RfE: German Locale de_DE

### ISSUE THREAD

**Issue by RainerBielefeld** [creecros/Group_assign#74]
Currently we only have a rudimentary Translation.php. I'm going to to contribute a complete one starting next weekend.

@creecros: any recommendation which existing one I should use as model?

**Comment by RainerBielefeld** [comment]
Started!

Can [this here ([kanboard/kanboard] PR run failed: Unit Tests - Update translations.php (9816944))](https://github.com/kanboard/kanboard/actions/runs/3488340824) also become an issue here? That's not my turf ...

**Comment by creecros** [comment]
nah all good

**Comment by RainerBielefeld** [comment]
It seems that this translation was rather useless. I am using Group_assign in KANBOARD in German Language with the old locale de_DE, and until now I did not see any action with untranslated strings in UI ...
