### ISSUE TITLE
RfE: French Locale fr_FR

### ISSUE THREAD

**Issue by RainerBielefeld** [creecros/Group_assign#76]
[Group_assign](https://github.com/creecros/Group_assign)/[Locale](https://github.com/creecros/Group_assign/tree/master/Locale)/[fr_FR](https://github.com/creecros/Group_assign/tree/master/Locale/fr_FR)/translations.php currently only has very few contents. I can complete translation to French language, will probably start weekend after de_DE will have been pulled to Master.

**Comment by creecros** [comment]
stale
