### ISSUE TITLE
Bug: Broken Version detection for Kanboard Nightly Builds

### ISSUE THREAD

**Issue by mundry** [creecros/Group_assign#78]
Hi,

For development builds of Kanboard, where the `APP_VERSION` is `main.<shortened git hash>`, the version detection of this plugin relies on the ChangeLog file to infer the latest release version.
However, the [ChangeLog has not been part of Docker builds](https://github.com/kanboard/kanboard/commit/6d2b2f4a793fe6f9321fa5ed164af1fd3520e01b) since version [1.2.9](https://github.com/kanboard/kanboard/releases/tag/v1.2.9) of Kanboard.

This breaks the version detection with Kanboard nightly Docker images, resulting in the wrong compatibility classes being loaded.

**Comment by creecros** [comment]
Might be time to stop supporting backward compatibility, or make it so it defaults to the latest code.

**Comment by creecros** [comment]
Ya, looks like my else statement is the old pre 1.2.5 code, cause I'm a dumb dumb, causing a greater chance to break, vs the 1 person in the world still using 1.2.4 and below with master version...
