### ISSUE TITLE
Plugin breaks colored categories in Kanboard 1.2.6

### ISSUE THREAD

**Issue by XBase-xOR** [creecros/Group_assign#8]
Kanboard 1.2.6 comes with a new feature for colored categories.

As soon as the Group_assign plugin is activated the feature no longer works (categories are simply displayed without colors on the board).

**Comment by creecros** [comment]
apparently it's more than that. Only other overrides were in the model and helper, probably in the model. I've been wanting to reduce the overrides anyway, which will make it more compatible in the long run, when i made this plugin, i knew less than i do now. It's gonna need an overhaul though to do it, so might take me longer than expected.

**Comment by creecros** [comment]
Band-aid for now.

**Comment by XBase-xOR** [comment]
Thx for the quick response and fix!
