### ISSUE TITLE
Group assign not populating

### ISSUE THREAD

**Issue by themagicm** [creecros/Group_assign#81]
Kanboard version   version: 1.2.26
PHP version: 7.4.33 
Group_assign version 1.82

When I am creating a new task, Groups show "unassigned" and no other groups are listed which prevents me from assigning a task to a group.

**Comment by creecros** [comment]
I would confirm a couple things.

1. Did you create any groups?
2. Did you give any groups permissions to said project?

**Comment by themagicm** [comment]
Smh. PEBKAC. Sorry.

-------- Original Message --------
